// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Estriper0/EventHub/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIEventService is a mock of IEventService interface.
type MockIEventService struct {
	ctrl     *gomock.Controller
	recorder *MockIEventServiceMockRecorder
}

// MockIEventServiceMockRecorder is the mock recorder for MockIEventService.
type MockIEventServiceMockRecorder struct {
	mock *MockIEventService
}

// NewMockIEventService creates a new mock instance.
func NewMockIEventService(ctrl *gomock.Controller) *MockIEventService {
	mock := &MockIEventService{ctrl: ctrl}
	mock.recorder = &MockIEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEventService) EXPECT() *MockIEventServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIEventService) Create(ctx context.Context, event *models.EventCreateRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIEventServiceMockRecorder) Create(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIEventService)(nil).Create), ctx, event)
}

// DeleteById mocks base method.
func (m *MockIEventService) DeleteById(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIEventServiceMockRecorder) DeleteById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIEventService)(nil).DeleteById), ctx, id)
}

// GetAll mocks base method.
func (m *MockIEventService) GetAll(ctx context.Context) ([]*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIEventServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIEventService)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockIEventService) GetById(ctx context.Context, id uuid.UUID) (*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIEventServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIEventService)(nil).GetById), ctx, id)
}

// Update mocks base method.
func (m *MockIEventService) Update(ctx context.Context, event *models.EventUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIEventServiceMockRecorder) Update(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIEventService)(nil).Update), ctx, event)
}
